import memoryGameBG from "../assets/images/memoryGameBG.png";
export const enteredToGameFrom = "enteredFromWaitingRoom";
export const userS = "user";
export const waitingRoomS = "waitingRoom";
export const tokenS = "token";
export const errorS = "error";
export const notFound = "404 not found";
export const stringS = "string";
export const serverError = "Server error, please try again later.";
export const failedToFetch = "Failed to fetch:";
export const memoryGameBGImage = memoryGameBG;
